// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// OptimizeMICL
S4 OptimizeMICL(S4 reference, StringVector name);
RcppExport SEXP _VarSelLCM_OptimizeMICL(SEXP referenceSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< StringVector >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(OptimizeMICL(reference, name));
    return rcpp_result_gen;
END_RCPP
}
// ComputeMICL
S4 ComputeMICL(S4 reference, StringVector name);
RcppExport SEXP _VarSelLCM_ComputeMICL(SEXP referenceSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< StringVector >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(ComputeMICL(reference, name));
    return rcpp_result_gen;
END_RCPP
}
// OptimizePenLike
S4 OptimizePenLike(S4 reference, double pen);
RcppExport SEXP _VarSelLCM_OptimizePenLike(SEXP referenceSEXP, SEXP penSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< double >::type pen(penSEXP);
    rcpp_result_gen = Rcpp::wrap(OptimizePenLike(reference, pen));
    return rcpp_result_gen;
END_RCPP
}
