# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

OptimizeMICL <- function(reference, name) {
    .Call('_VarSelLCM_OptimizeMICL', PACKAGE = 'VarSelLCM', reference, name)
}

ComputeMICL <- function(reference, name) {
    .Call('_VarSelLCM_ComputeMICL', PACKAGE = 'VarSelLCM', reference, name)
}

OptimizePenLike <- function(reference, pen) {
    .Call('_VarSelLCM_OptimizePenLike', PACKAGE = 'VarSelLCM', reference, pen)
}

